### ISSUE TITLE
请问这个短域名跳转系统怎么使用？

### ISSUE THREAD

**Issue by fengzhao** [k4yt3x/akasio-go#1]
按照你的用法，在自己的服务器上部署了，并nginx反代到本地的akaio的8000端口，401未授权，还有，请问具体怎么设置长域名和短域名的map映射？

**Comment by k4yt3x** [comment]
如果您设置的 hostname 不等于客户端访问的 hostname，akasio 就会返回 401 Unauthorized 以防止 hostname spoofing。如果您的网站域名是 example.com，那么 akasio 的启动参数就要加上 `-n example.com`。具体的代码段在这里：

https://github.com/k4yt3x/akasio-go/blob/395482b17235dacb09adbca395a8fbe6303a2b20/cmd/akasio/main.go#L69-L75

如果需要本地调试的话，可以用 `-d` 参数开启 debug 模式禁用所有安全检查。

---

具体的映射设置大概张这样，例如我想让 example.com/**g** 跳转到 https://www.google.com：

```json
{
    "/g": "https://www.google.com"
}
```

左边的 key 是短链接地址，右边的 value 是跳转目标地址。

**Comment by fengzhao** [comment]
抱歉，我还是有点问题没理解，请问这个短域名的301跳转跟nginx的 proxy_pass 有什么区别？

而且，我的域名 example.com  访问本身就是在 nginx 上，我启动了 akaio ， 我访问 example.com/g  他还是会去找nginx啊，并且返回404

有点疑惑

**Comment by k4yt3x** [comment]
这个短域名跳转是 301，`proxy_pass` 是个反向代理，Nginx 只负责把 HTTP 请求传递给 akasio 而已，其本身不应该承担任何返回结果的计算。

**Comment by k4yt3x** [comment]
Closed due to inactivity.
